name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        working-directory: backend
        run: mvn clean compile

      - name: Run unit tests
        working-directory: backend
        run: mvn test -Dtest="*ServiceTest,BackendApplicationTests"

      - name: Run integration tests
        working-directory: backend
        run: mvn test -Dtest="*ApiTest"

      - name: Setup Node.js for frontend
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Build frontend for CI
        working-directory: frontend
        run: npm run build

      - name: Preview frontend (simulates prod environment)
        working-directory: frontend
        run: |
          npm run preview -- --port 5173 --host 0.0.0.0 &
          echo "Frontend preview started"
          
      - name: Wait for frontend to be ready
        run: |
          echo "Waiting for frontend to start..."
          timeout 30s bash -c 'until curl -f http://localhost:5173; do sleep 2; done'
          echo "Frontend is ready"

      - name: Setup Chrome for UI tests
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Run UI automation tests
        working-directory: backend
        run: mvn test -Dtest="*UITest" -Dwebdriver.chrome.args="--headless,--no-sandbox,--disable-dev-shm-usage,--disable-gpu,--window-size=1920,1080"
        env:
          DISPLAY: ":99"

      - name: Run BDD tests
        working-directory: backend
        run: mvn test -Dtest="CucumberTest"

      - name: Generate test report
        working-directory: backend
        run: mvn surefire-report:report
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: backend/target/surefire-reports/
