name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build project
        working-directory: backend
        run: mvn clean compile

      - name: Run unit tests
        working-directory: backend
        run: mvn test -Dtest="*Test,!*UITest"

      - name: Run integration tests
        working-directory: backend
        run: mvn test -Dtest="*ApiTest"

      - name: Setup Chrome for UI tests
        uses: browser-actions/setup-chrome@latest

      - name: Start frontend for UI tests
        run: |
          cd frontend
          npm ci
          npm run dev &
          sleep 10

      - name: Run UI automation tests
        working-directory: backend
        run: mvn test -Dtest="*UITest"

      - name: Run BDD tests
        working-directory: backend
        run: mvn test -Dtest="CucumberTest"

      - name: Generate test report
        working-directory: backend
        run: mvn surefire-report:report
        if: always()

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: backend/target/surefire-reports/
